export interface QrGenerateRequest {
  /**
   * URL that the QR code will point to.
   */
  url: string;

  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  /**
   * Number of variants to generate.
   *
   * Note: Generating more variants will take longer.
   */
  num_variants?: number;
}

export interface QrGenerateResponse {
  /**
   * URL of the QR code images that was generated by the model.
   */
  image_urls: string[];

  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;
}
